version: "3.9"
services:
  postgres12:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres12:5432/blog?sslmode=disable  
    depends_on:
      - postgres12
    entrypoint: [ "/app/wait-for.sh", "postgres12:5432", "--", "/app/start.sh"]
    command: [ "/app/main" ]
