// Code generated by sqlc. DO NOT EDIT.

package sqlc_db

import (
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID       uuid.UUID `json:"id"`
	Title    string    `json:"title"`
	Body     string    `json:"body"`
	PostedAt time.Time `json:"posted_at"`
	AuthorID uuid.UUID `json:"author_id"`
}

type Author struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}
